config/routes.rb
Rails.application.routes.draw do
  root :to => redirect("/topics")

  resources :topics do
    resources :candidates do
      member do
        post :move_higher
        post :move_lower
      end
    end
    resources :view_points do
      member do
        post :move_higher
        post :move_lower
      end
    end
    resources :factors
  end
end

app/models/view_point.rb
class ViewPoint < ActiveRecord::Base
  belongs_to :topic, counter_cache: true
  has_many :factors, dependent: :destroy
  acts_as_list scope: :topic

  validates :title, presence: true, allow_blank: false
  validates :title, uniqueness: { scope: :topic }
end

app/controllers/view_points_controller.rb
class ViewPointsController < ApplicationController
  before_action :set_view_point_and_topic, only: [
    :show, :edit, :update, :destroy, :move_higher, :move_lower]

  include Axis

  def index
    @topic = Topic.includes(view_points: [:topic]).find(params[:topic_id])
    @view_points = @topic.view_points
  end

  def show
  end

  def new
    @view_point = ViewPoint.new(topic_id: params[:topic_id])
    @topic = @view_point.topic
  end

  def edit
  end

  def create
    create_view_point_and_topic
    notice = "New view point '#{@view_point.title}' was created."
    process_create(@view_point, notice)
  end

  def update
    notice = "The view point '#{@view_point.title}' was updated."
    process_update(@view_point, view_point_params, notice)
  end

  def destroy
    notice = "The view point '#{@view_point.title}' was destroyed."
    process_destroy(@view_point, notice)
  end

  def move_higher
    @view_point.move_higher
    redirect_to topic_path(@topic)
  end

  def move_lower
    @view_point.move_lower
    redirect_to topic_path(@topic)
  end

  private

  def set_view_point_and_topic
    @view_point = ViewPoint.find(params[:id])
    @topic = @view_point.topic
  end

  def create_view_point_and_topic
    params_with_topic_id = view_point_params.merge(topic_id: params[:topic_id])
    @view_point = ViewPoint.new(params_with_topic_id)
    @topic = @view_point.topic
  end

  def view_point_params
    params.require(:view_point).permit(:title)
  end
end

app/helpers/view_points_helper.rb
module ViewPointsHelper
end

app/views/view_points/_form.html.erb
<%= simple_form_for [@topic, @view_point], :html => { :class => "form-horizontal" } do |f| %>
  <div class="row">
    <%= f.input :title,
                required: false,
                label_html: { class: "col-xs-12 col-sm-1" },
                input_html: { class: "col-xs-12 col-sm-11" } %>
    <%= error_span(@view_point[:title]) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save", :class => "btn btn-primary" %>

    <%= link_to "Cancel", topic_path(@topic), :class => "btn btn-default" %>
  </div>

  <div class="form-actions">
    <% if @view_point.id %>
      <%= link_to "Destroy", topic_view_point_path(@view_point.topic, @view_point),
                    :method => "delete",
                    :data => { :confirm => "Are you sure?" },
                    :class => "btn btn-danger" %>
    <% end %>
  </div>
<% end %>

app/views/view_points/edit.html.erb
<%- model_class = ViewPoint -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/view_points/index.html.erb
<%- model_class = ViewPoint -%>
<div class="page-header">
  <h1>
    View Points - <%= @topic.title %>
  </h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @view_points.each do |view_point| %>
      <tr>
        <td><%= link_to view_point.title, topic_view_point_path(view_point.topic, view_point) %></td>
        <td><%= to_display_time(view_point.created_at) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_topic_view_point_path(view_point.topic, view_point),
                      :class => 'btn btn-default btn-xs' %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      topic_view_point_path(view_point.topic, view_point),
                      :method => :delete,
                      :data => {
                        :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))
                      },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_topic_view_point_path,
            :class => 'btn btn-primary' %>

<%= link_to t('.back', :default => t("helpers.links.back")),
            topic_path(@topic), :class => 'btn btn-default'  %>

app/views/view_points/new.html.erb
<%- model_class = ViewPoint -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/view_points/show.html.erb
<%- model_class = ViewPoint -%>
<div class="page-header">
  <h1><%=t ".title", :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @view_point.title %></dd>
</dl>

<%= link_to "Edit",
            edit_topic_view_point_path(@view_point.topic, @view_point), :class => "btn btn-default" %>

<%= link_to "Destroy",
              topic_view_point_path(@view_point.topic, @view_point),
              :method => "delete",
              :data => { :confirm => "Are you sure?" },
              :class => "btn btn-danger" %>

<%= link_to "Back",
            topic_view_points_path(@topic), :class => "btn btn-default"  %>