config/routes.rb
Rails.application.routes.draw do
  root :to => redirect("/topics")

  resources :topics do
    resources :candidates do
      member do
        post :move_higher
        post :move_lower
      end
    end
    resources :view_points do
      member do
        post :move_higher
        post :move_lower
      end
    end
    resources :factors
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :view_points, -> { order(:position) }, dependent: :destroy
  has_many :candidates,  -> { order(:position) }, dependent: :destroy
  has_many :factors, dependent: :destroy

  validates :title, presence: true, allow_blank: false
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:edit, :update, :destroy]

  def index
    @topics = Topic.order("updated_at DESC")
  end

  def show
    @topic = Topic.includes(candidates: [:topic])
      .includes(view_points: [:topic])
      .includes(factors: [:view_point, :candidate])
      .find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        notice = "Topic was successfully created."
        format.html { redirect_to @topic, notice: notice }
      else
        format.html { redirect_to new_topic_path }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        notice = "Topic was successfully updated."
        format.html { redirect_to @topic, notice: notice }
      else
        format.html { redirect_to edit_topic_path }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      notice = "Topic was successfully destroyed."
      format.html { redirect_to topics_url, notice: notice }
    end
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :description, :comment)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= simple_form_for @topic, :html => { :class => "form-horizontal" } do |f| %>
  <div class="row">
    <%= f.input :title,
                label_html: { class: "col-xs-12 col-sm-2" },
                input_html: { class: "col-xs-12 col-sm-10" } %>
    <%= error_span(@topic[:title]) %>
  </div>

  <div class="row">
    <%= f.input :description,
                label_html: { class: "col-xs-12 col-sm-2" },
                input_html: { class: "col-xs-12 col-sm-10" } %>
    <%= error_span(@topic[:description]) %>
  </div>

  <div class="row">
    <%= f.input :comment,
                as: :text,
                label_html: { class: "col-xs-12 col-sm-2" },
                input_html: { class: "col-xs-12 col-sm-10", rows: 15 } %>
    <%= error_span(@topic[:comment]) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save", :class => "btn btn-primary" %>
    <%= link_to "Cancel", topics_path(@topic), :class => "btn btn-default" %>
  </div>
<% end %>

app/views/topics/_show_candidate.html.erb
<% if candidate.first? %>
    <i class="fa fa-arrow-left inactive"></i>
<% else %>
  <%= link_to move_higher_topic_candidate_path(candidate.topic, candidate),
        :method => :post, :id => "candidate_move_higher_#{candidate.id}" do %>
    <i class="fa fa-arrow-left"></i>
  <% end %>
<% end %>

<% if candidate.last? %>
    <i class="fa fa-arrow-right inactive"></i>
<% else %>
  <%= link_to move_lower_topic_candidate_path(candidate.topic, candidate),
        :method => :post, :id => "candidate_move_lower_#{candidate.id}" do %>
    <i class="fa fa-arrow-right"></i>
  <% end %>
<% end %>

<%= link_to candidate.title,
            edit_topic_candidate_path(@topic, candidate),
            class: "candidate_link" %>

app/views/topics/_show_summary.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><b>Summary</b></div>
  <table class="table table-bordered">
    <tr>
      <th class="col-md-2 active">Title</th>
      <td class="col-md-10"><%= topic.title %></td>
    </tr>
    <tr>
      <th class="col-md-2 active">Description</th>
      <td class="col-md-10"><%= topic.description %></td>
    </tr>
    <tr>
      <th class="col-md-2 active">Comment</th>
      <td class="col-md-10"><%= simple_format(topic.comment) %></td>
    </tr>
  </table>
</div>

app/views/topics/_show_view_point.html.erb
<% if view_point.first? %>
    <i class="fa fa-arrow-up inactive"></i>
<% else %>
  <%= link_to move_higher_topic_view_point_path(view_point.topic, view_point),
        :method => :post, :id => "view_point_move_higher_#{view_point.id}" do %>
    <i class="fa fa-arrow-up"></i>
  <% end %>
<% end %>

<% if view_point.last? %>
    <i class="fa fa-arrow-down inactive"></i>
<% else %>
  <%= link_to move_lower_topic_view_point_path(view_point.topic, view_point),
        :method => :post, :id => "view_point_move_lower_#{view_point.id}" do %>
    <i class="fa fa-arrow-down"></i>
  <% end %>
<% end %>

<%= link_to view_point.title,
            edit_topic_view_point_path(@topic, view_point),
            class: "view_point_link" %>

app/views/topics/edit.html.erb
<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/topics/index.html.erb
<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.title, topic_path(topic) %></td>
        <td><%= topic.description %></td>
        <td><%= to_display_time(topic.updated_at) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_topic_path(topic), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      topic_path(topic),
                      :method => :delete,
                      :data => {
                        :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))
                      },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_topic_path,
            :class => 'btn btn-primary' %>

app/views/topics/new.html.erb
<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/topics/show.html.erb
<%- model_class = Topic -%>
<div class="page-header">
  <h1>Topic</h1>
</div>

<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

<%= render :partial => "show_summary", locals: {topic: @topic} %>

<div class="panel panel-default">
  <div class="panel-heading">
    <b>Matrix of </b> <%= link_to pluralize(@topic.factors_count, "merit factors"), topic_factors_path(@topic) %>
  </div>
  <table class="table table-bordered table-hover">
    <tr>
      <td rowspan="2" colspan="2"></td>
      <td align="center" colspan="2">
        <%= link_to topic_candidates_path(@topic) do %>
          <%= pluralize(@topic.candidates_count, "candidate") %>
        <% end %>
      </td>
    </tr>
    <tr>
      <% @topic.candidates.each do |candidate| %>
        <td>
          <%= render :partial => "show_candidate", locals: {candidate: candidate} %>
        </td>
      <% end %>
    </tr>

    <% @topic.view_points.each_with_index do |view_point, index| %>
      <tr>
        <% if index == 0 %>
          <td rowspan="<%= @topic.view_points.count %>" class="matrix-header">
            <%= link_to topic_view_points_path(@topic) do %>
              <%= pluralize(@topic.view_points_count, "view point") %>
            <% end %>
          </td>
        <% end %>

        <td>
          <%= render :partial => "show_view_point", locals: {view_point: view_point} %>
        </td>

        <% @topic.candidates.each do |candidate| %>
          <td>
            <ul>
              <% factors = @topic.factors.select { |f| f.view_point == view_point && f.candidate == candidate } %>
              <% factors.each do |factor| %>
                <li>
                  <%= link_to edit_topic_factor_path(@topic, factor) do %>
                    <span class="<%= factor.score_name.downcase %>"><%= factor.title %></span>
                  <% end %>

                  <% if factor.description != "" %>
                    <%= link_to '#',
                      "class": "has-popover",
                      "data-toggle": "popover",
                      "data-content": factor.description do %>
                      <i class="fa fa-comment-o"></i>
                    <% end %>
                  <% end %>
                </li>
              <% end %>
            </ul>
            <%= link_to new_topic_factor_path(@topic, view_point: view_point, candidate: candidate) do %>
              <i class="fa fa-edit"></i>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

<div class="form-actions">
  <%= link_to "New View Point",
              new_topic_view_point_path(@topic), :class => "btn btn-success" %>

  <%= link_to "New Candidate",
              new_topic_candidate_path(@topic), :class => "btn btn-success" %>

  <%= link_to "New Factor",
              new_topic_factor_path(@topic), :class => "btn btn-success" %>
</div>

<div class="form-actions">
  <%= link_to "Edit Topic",
              edit_topic_path(@topic), :class => "btn btn-default" %>

  <%= link_to "Back",
              topics_path, :class => "btn btn-default" %>
</div>

<div class="form-actions">
  <%= link_to "Destroy Topic",
              topic_path(@topic),
              :method => "delete",
              :data => { :confirm => "Are you sure?" },
              :class => "btn btn-danger" %>
</div>