config/routes.rb
Rails.application.routes.draw do
  root :to => redirect("/topics")

  resources :topics do
    resources :candidates do
      member do
        post :move_higher
        post :move_lower
      end
    end
    resources :view_points do
      member do
        post :move_higher
        post :move_lower
      end
    end
    resources :factors
  end
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  belongs_to :topic, counter_cache: true
  has_many :factors, dependent: :destroy
  acts_as_list scope: :topic

  validates :title, presence: true, allow_blank: false
  validates :title, uniqueness: { scope: :topic }
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate_and_topic, only: [
    :show, :edit, :update, :destroy, :move_higher, :move_lower]

  include Axis

  def index
    @topic = Topic.includes(candidates: [:topic]).find(params[:topic_id])
    @candidates = @topic.candidates
  end

  def show
  end

  def new
    @candidate = Candidate.new(topic_id: params[:topic_id])
    @topic = @candidate.topic
  end

  def edit
  end

  def create
    create_candidate_and_topic
    notice = "New candidate '#{@candidate.title}' was created."
    process_create(@candidate, notice)
  end

  def update
    notice = "The candidate '#{@candidate.title}' was updated."
    process_update(@candidate, candidate_params, notice)
  end

  def destroy
    notice = "The candidate '#{@candidate.title}' was destroyed."
    process_destroy(@candidate, notice)
  end

  def move_higher
    @candidate.move_higher
    redirect_to topic_path(@topic)
  end

  def move_lower
    @candidate.move_lower
    redirect_to topic_path(@topic)
  end

  private

  def set_candidate_and_topic
    @candidate = Candidate.find(params[:id])
    @topic = @candidate.topic
  end

  def create_candidate_and_topic
    params_with_topic_id = candidate_params.merge(topic_id: params[:topic_id])
    @candidate = Candidate.new(params_with_topic_id)
    @topic = @candidate.topic
  end

  def candidate_params
    params.require(:candidate).permit(:title)
  end
end

app/views/candidates/_form.html.erb
<%= simple_form_for [@topic, @candidate], :html => { :class => "form-horizontal" } do |f| %>
  <div class="row">
    <%= f.input :title,
                required: false,
                label_html: { class: "col-xs-12 col-sm-2" },
                input_html: { class: "col-xs-12 col-sm-10" } %>
    <%= error_span(@candidate[:title]) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save", :class => "btn btn-primary" %>

    <%= link_to "Cancel", topic_path(@topic), :class => "btn btn-default" %>
  </div>

  <div class="form-actions">
    <% if @candidate.id %>
      <%= link_to "Destroy", topic_candidate_path(@candidate.topic, @candidate),
                    :method => "delete",
                    :data => { :confirm => "Are you sure?" },
                    :class => "btn btn-danger" %>
    <% end %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<%- model_class = Candidate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/candidates/index.html.erb
<%- model_class = ViewPoint -%>
<div class="page-header">
  <h1>
    Candidates - <%= @topic.title %>
  </h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= link_to candidate.title, topic_candidate_path(candidate.topic, candidate) %></td>
        <td><%= to_display_time(candidate.created_at) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_topic_candidate_path(candidate.topic, candidate),
                      :class => 'btn btn-default btn-xs' %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      topic_candidate_path(candidate.topic, candidate),
                      :method => :delete,
                      :data => {
                        :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))
                      },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_topic_candidate_path,
            :class => 'btn btn-primary' %>

<%= link_to t('.back', :default => t("helpers.links.back")),
            topic_path(@topic), :class => 'btn btn-default'  %>

app/views/candidates/new.html.erb
<%- model_class = Candidate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/candidates/show.html.erb
<%- model_class = Candidate -%>
<div class="page-header">
  <h1><%=t ".title", :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @candidate.title %></dd>
</dl>

<%= link_to "Edit",
             edit_topic_candidate_path(@candidate.topic, @candidate), :class => "btn btn-default" %>

<%= link_to "Destroy",
            topic_candidate_path(@candidate.topic, @candidate),
            :method => "delete",
            :data => { :confirm => "Are you sure?" },
            :class => "btn btn-danger" %>

<%= link_to "Back",
            topic_candidates_path(@topic), :class => "btn btn-default" %>